# Generated by Django 5.1.5 on 2025-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_order_quanity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_quanity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
