# Generated by Django 5.1.5 on 2025-01-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_order_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_quanity',
            new_name='order_quantity',
        ),
    ]
