# Generated by Django 5.1.5 on 2025-01-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_order_quanity_order_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_quantity',
            new_name='order_quanity',
        ),
    ]
