# Generated by Django 5.1.5 on 2025-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_order_quantity_order_order_quanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
