# Generated by Django 5.1.5 on 2025-01-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discounted_price',
            new_name='discount',
        ),
    ]
