# Generated by Django 5.1.5 on 2025-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_discounted_price_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('Delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
