# Generated by Django 5.1.5 on 2025-02-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
