# Generated by Django 5.1.5 on 2025-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='in_gujarat',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
    ]
