# Generated by Django 5.1.5 on 2025-02-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customuser_in_gujarat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='docker_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
