# Generated by Django 5.1.5 on 2025-02-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_docker_number_order_docket_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='freight',
            field=models.FloatField(default=100),
        ),
    ]
