# Generated by Django 5.1.5 on 2025-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_order_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='GSTIN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
