# Generated by Django 5.1.5 on 2025-02-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customuser_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='GSTIN',
        ),
    ]
