# Generated by Django 5.1.5 on 2025-02-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_customuser_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
