# Generated by Django 4.2.3 on 2025-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_courier_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_serial', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
