# Generated by Django 4.2.3 on 2025-02-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_stockproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockProduct',
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalogheading')),
                ('catalog_subheading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalogsubheading')),
            ],
        ),
    ]
